### PR TITLE
Add `MockXhr` and `xhrFactory` fields to the MockXhrServer TS defs

### LINKED ISSUE #23: `MockXhr` and `xhrFactory` not available in the TypeScript definitions
**Is this issue a *feature* request or a *bug* report?**
Bug

**What is the current behavior?**
`MockXhrServer.MockXhr` and `MockXhrServer.xhrFactory` not available in the TypeScript definitions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
These are available when interfacing with the library in TypeScript

**Environment in which you encounter the issue:**

- mock-xmlhttprequest version: 7.0.2
- Node.js version: 12.19.0
- OS version: macOS 10.15.7

**Did this work in a previous version of mock-xmlhttprequest (which)?**
Unsure.

**Do you intend to provide a pull request to address this issue?**
Yes

### PR DESCRIPTION
**Pull request by dkozma**
**Please make sure to run the tests (including linter)**

## Summary of proposed changes
Add `MockXhr` and `xhrFactory` fields to the MockXhrServer TS definitions.

## Issue
Fixes #23 .

## Details
*Longer description if relevant*

## How to test the changes
*Added tests, etc.*

### CODE REVIEW

**Comment by berniegp** [comment]
Thanks so much for this! I'll just test it before merging, but everything looks good.

I'm guessing a package release would make your life easier after this is merged? I don't have any other planned releases in the short-term so I could publish a new version soon for this if so.

**Comment by dkozma** [comment]
@berniegp A package release would be super helpful, I'd appreciate it if you would be able to publish one. Thanks for this library! Really comes in handy for mocking RxJS Ajax observables.

**Comment by berniegp** [comment]
Thanks again @dkozma! 7.0.3 is out now.

**Comment by dkozma** [comment]
Awesome, thank you @berniegp !

**Pull request merged**
